import { StyleSheet } from 'react-native';
import { colors, fonts, spacing, borderRadius, shadows } from './theme';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: spacing.lg,
  },
  title: {
    fontSize: fonts.size.xxxl,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.xxxl * fonts.lineHeight.tight,
    color: colors.text,
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    ...shadows.sm,
  },
  addButtonText: {
    color: colors.surface,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.md,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    flex: 1,
    marginRight: spacing.sm,
    backgroundColor: colors.surface,
  },
  dayBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    marginHorizontal: spacing.lg,
    backgroundColor: colors.card,
    ...shadows.md,
  },
  dayName: {
    fontSize: fonts.size.xl,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.xl * fonts.lineHeight.tight,
    color: colors.text,
    marginBottom: 0,
  },
  exerciseCountBadge: {
    backgroundColor: colors.primaryLight,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.sm,
    borderRadius: borderRadius.lg,
    marginLeft: spacing.sm,
  },
  badgeText: {
    fontSize: fonts.size.xs,
    fontWeight: fonts.weight.semibold,
    color: colors.text,
  },
  dayActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
    marginTop: spacing.lg,
    paddingTop: spacing.md,
    borderTopWidth: 1,
    borderTopColor: colors.borderLight,
  },
  actionBtn: {
    paddingVertical: spacing.sm,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    marginLeft: spacing.md,
    minWidth: 78,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.sm,
  },
  actionBtnText: {
    fontSize: fonts.size.sm,
    fontWeight: fonts.weight.bold,
  },
  primaryBtn: {
    backgroundColor: colors.primary,
  },
  primaryBtnText: {
    color: '#fff',
  },
  dangerBtn: {
    backgroundColor: colors.danger,
    borderWidth: 0,
  },
  dangerBtnText: {
    color: '#fff',
  },
  exerciseSection: {
    marginTop: spacing.lg,
    paddingTop: spacing.lg,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  exerciseTitle: {
    fontSize: fonts.size.lg,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.lg * fonts.lineHeight.tight,
    color: colors.text,
    marginBottom: spacing.lg,
  },
  exerciseBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.md,
    padding: spacing.md,
    marginBottom: spacing.sm,
    backgroundColor: '#F5F5F5',
    ...shadows.sm,
  },
  exerciseName: {
    fontSize: fonts.size.md,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.md * fonts.lineHeight.normal,
    color: colors.text,
    marginBottom: 2,
  },
  exerciseDetails: {
    fontSize: fonts.size.sm,
    color: colors.textMuted,
    lineHeight: fonts.size.sm * fonts.lineHeight.normal,
    marginBottom: spacing.xs,
  },
  exerciseNotes: {
    fontSize: fonts.size.sm,
    color: colors.textMuted,
    lineHeight: fonts.size.sm * fonts.lineHeight.normal,
    marginBottom: spacing.xs,
    fontStyle: 'italic',
  },
  exerciseActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginLeft: spacing.sm,
    padding: spacing.sm,
    borderRadius: borderRadius.round,
  },
  deleteText: {
    color: colors.danger,
    fontWeight: fonts.weight.semibold,
    fontSize: fonts.size.sm,
  },
  deleteTextSmall: {
    color: colors.danger,
    fontWeight: fonts.weight.semibold,
    fontSize: fonts.size.xs,
    marginRight: spacing.sm,
  },
  addExerciseLink: {
    color: colors.primary,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.md,
  },
  modalButton: {
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.md,
    ...shadows.sm,
  },
  textInput: {
    height: 40,
    fontSize: fonts.size.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    textAlignVertical: 'center',
  },
  textInputMultiline: {
    minHeight: 60,
    fontSize: fonts.size.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    textAlignVertical: 'top',
  },
});

export default styles;
