import { StyleSheet } from 'react-native';
import { colors, fonts, spacing, borderRadius, shadows } from './theme';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
    padding: spacing.lg,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  title: {
    fontSize: fonts.size.xxxl,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.xxxl * fonts.lineHeight.tight,
    color: colors.text,
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderRadius: borderRadius.md,
    ...shadows.md,
  },
  addButtonText: {
    color: colors.surface,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.md,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: '#ccc',
    padding: 8,
    borderRadius: 4,
    flex: 1,
    marginRight: 8,
  },
  splitBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.lg,
    padding: spacing.xl,
    marginBottom: spacing.lg,
    backgroundColor: colors.card,
    ...shadows.sm,
  },
  splitName: {
    fontSize: fonts.size.lg,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.lg * fonts.lineHeight.tight,
    color: colors.text,
    marginBottom: spacing.sm,
  },
  modeBadge: {
    backgroundColor: '#e6f0ff',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
    marginLeft: 10,
  },
  currentBadge: {
    backgroundColor: '#dff6e0',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 14,
    marginLeft: 10,
  },
  badgeText: {
    fontSize: fonts.size.xs,
    fontWeight: fonts.weight.semibold,
    color: colors.text,
  },
  splitActions: {
    flexDirection: 'row',
    marginTop: 8,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  deleteBtn: {
    color: 'red',
    marginLeft: 16,
  },
  splitDaysSection: {
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
  splitDaysTitle: {
    fontSize: fonts.size.md,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.md * fonts.lineHeight.normal,
    color: colors.text,
    marginBottom: spacing.md,
  },
  splitDayBox: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  addDayBtn: {
    backgroundColor: '#e0e0e0',
    borderRadius: 6,
    padding: 8,
    marginBottom: 6,
  },
  addDayBtnText: {
    color: colors.text,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.sm,
  },
  assignBtn: {
    backgroundColor: '#eee',
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 6,
    marginHorizontal: 6,
  },
  assignBtnText: {
    color: colors.primary,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.sm,
  },
  modeButton: {
    paddingVertical: 8,
    paddingHorizontal: 16,
    borderRadius: 8,
    flex: 1,
  },
  daySelectItem: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginBottom: 8,
  },
  modalButton: {
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
  },
  tabButton: {
    flex: 1,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignItems: 'center',
  },
  actionBtn: {
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginLeft: 10,
    minWidth: 78,
    alignItems: 'center',
    justifyContent: 'center',
  },
  actionBtnText: {
    fontSize: fonts.size.sm,
    fontWeight: fonts.weight.bold,
  },
  primaryBtn: {
    backgroundColor: '#007AFF',
  },
  primaryBtnText: {
    color: '#fff',
  },
  dangerBtn: {
    backgroundColor: '#ff3b30',
    borderWidth: 0,
  },
  dangerBtnText: {
    color: '#fff',
  },
  durationBadge: {
    backgroundColor: '#e6f0ff',
    paddingVertical: 6,
    paddingHorizontal: 10,
    borderRadius: 12,
    marginRight: 8,
  },
  durationText: {
    fontSize: fonts.size.sm,
    fontWeight: fonts.weight.bold,
    color: colors.primary,
  },
  splitFooter: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 12,
  },
  removeWrapper: {
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
    height: 36,
  },
  linkText: {
    color: colors.primary,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.sm,
  },
  removeTextStyle: {
    color: colors.danger,
    fontWeight: fonts.weight.semibold,
    fontSize: fonts.size.xs,
  },
});
