import { StyleSheet } from 'react-native';
import { colors, fonts, spacing, borderRadius, shadows } from './theme';

const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.lg,
  },
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  title: {
    fontSize: fonts.size.xxxl,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.xxxl * fonts.lineHeight.tight,
    color: colors.text,
    marginBottom: spacing.lg,
  },
  sectionTitle: {
    fontSize: fonts.size.lg,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.lg * fonts.lineHeight.tight,
    color: colors.text,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    padding: spacing.md,
    borderRadius: borderRadius.md,
    flex: 1,
    marginRight: spacing.sm,
    marginBottom: spacing.sm,
    backgroundColor: colors.surface,
  },
  exerciseBox: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: borderRadius.lg,
    padding: spacing.lg,
    paddingBottom: 40,
    marginBottom: spacing.lg,
    marginHorizontal: spacing.lg,
    backgroundColor: colors.card,
    ...shadows.sm,
  },
  exerciseTitle: {
    fontSize: fonts.size.md,
    fontWeight: fonts.weight.bold,
    lineHeight: fonts.size.md * fonts.lineHeight.normal,
    color: colors.text,
    marginBottom: 0,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: colors.overlay,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.lg,
  },
  modalContent: {
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xl,
    padding: spacing.xl,
    ...shadows.lg,
    maxWidth: 400,
    width: '100%',
    alignItems: 'center',
  },
  modalButton: {
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    marginLeft: spacing.sm,
    backgroundColor: colors.backgroundMuted,
  },
  modalButtonText: {
    color: colors.text,
    fontWeight: '600',
  },
  addButton: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: borderRadius.md,
    ...shadows.sm,
  },
  addButtonText: {
    color: colors.surface,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.md,
  },
  textInput: {
    height: 40,
    fontSize: fonts.size.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    textAlignVertical: 'center',
  },
  textInputMultiline: {
    minHeight: 60,
    fontSize: fonts.size.md,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.sm,
    textAlignVertical: 'top',
  },
  unitSwitchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginLeft: 8,
    minWidth: 96,
    height: 40,
  },
  unitLabel: {
    fontSize: fonts.size.xs,
    color: colors.textMuted,
    marginBottom: spacing.xs,
    textAlign: 'center',
  },
  unitToggleBtn: {
    height: 40,
    paddingHorizontal: spacing.md,
    borderRadius: borderRadius.md,
    backgroundColor: colors.backgroundMuted,
    marginRight: spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    minWidth: 48,
  },
  unitToggleBtnActive: {
    backgroundColor: colors.primary,
  },
  unitToggleText: {
    color: colors.text,
    fontWeight: fonts.weight.semibold,
    fontSize: fonts.size.sm,
  },
  unitToggleTextActive: {
    color: colors.background,
  },
  goalBadge: {
    position: 'absolute',
    right: spacing.md,
    top: spacing.sm,
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    borderRadius: borderRadius.lg,
    ...shadows.sm,
  },
  goalBadgeText: {
    color: colors.surface,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.xs,
  },
  bodyweightBtn: {
    marginLeft: 'auto',
    width: 44,
    height: 44,
    borderRadius: borderRadius.round,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    ...shadows.sm,
  },
  bodyweightIcon: {
    fontSize: 20,
    color: colors.background,
  },
  removeBtn: {
    marginLeft: 8,
    paddingHorizontal: 4,
    paddingVertical: 0,
    // align vertically to center of inputs
    width: 40,
    height: 40,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: -8,
  },
  removeBtnText: {
    color: colors.danger,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.lg,
  },
  setRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    minHeight: 44,
  },
  setLabel: {
    width: 64,
    fontSize: fonts.size.sm,
    fontWeight: fonts.weight.semibold,
    color: colors.textMuted,
    marginRight: spacing.sm,
    height: 40,
    lineHeight: 40,
  },
  inputWeight: {
    width: 100,
    marginRight: 8,
    height: 40,
    paddingVertical: 6,
    textAlignVertical: 'center',
  },
  inputReps: {
    width: 80,
    marginRight: 8,
    height: 40,
    paddingVertical: 6,
    textAlignVertical: 'center',
  },
  addSetLink: {
    marginBottom: 8,
  },
  addSetText: {
    color: colors.primary,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.sm,
  },
  addExerciseBtn: {
    marginTop: 0,
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 6,
    alignSelf: 'flex-start',
    backgroundColor: 'transparent',
  },
  addExerciseText: {
    color: colors.primary,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.md,
  },
  notesInput: {
    marginTop: 8,
  },
  saveButtonWrap: {
    marginTop: 10,
    alignSelf: 'flex-start',
  },
  exerciseTitleInput: {
    fontSize: fonts.size.md,
    fontWeight: fonts.weight.bold,
    color: colors.text,
    marginBottom: spacing.sm,
    borderBottomWidth: 1,
    borderBottomColor: 'transparent',
    paddingVertical: 2,
  },
  titleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  editPencil: {
    marginLeft: spacing.sm,
    width: 28,
    height: 28,
    borderRadius: borderRadius.round,
    backgroundColor: colors.backgroundMuted,
    alignItems: 'center',
    justifyContent: 'center',
  },
  editPencilText: {
    fontSize: 14,
  },
  removeExerciseBtn: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 6,
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeExerciseText: {
    color: colors.danger,
    fontWeight: fonts.weight.semibold,
    fontSize: fonts.size.xs,
  },
  removeExerciseAbsolute: {
    position: 'absolute',
    right: 10,
    bottom: 10,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 6,
    backgroundColor: 'transparent',
  },
  checkbox: {
    width: 28,
    height: 28,
    borderRadius: borderRadius.sm,
    borderWidth: 1,
    borderColor: colors.border,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  checkboxChecked: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkboxText: {
    color: colors.surface,
    fontWeight: fonts.weight.bold,
  },
  inputDisabled: {
    backgroundColor: colors.backgroundMuted,
    color: colors.textMuted,
    opacity: 0.6,
  },
  primaryButton: {
    backgroundColor: colors.primary,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.md,
    ...shadows.md,
  },
  primaryButtonDisabled: {
    backgroundColor: colors.backgroundMuted,
    opacity: 0.5,
  },
  primaryButtonText: {
    color: colors.surface,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.md,
  },
  primaryButtonTextDisabled: {
    color: colors.textMuted,
  },
  secondaryButton: {
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
    paddingVertical: spacing.md,
    paddingHorizontal: spacing.lg,
    borderRadius: borderRadius.lg,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: spacing.sm,
    ...shadows.sm,
  },
  secondaryButtonDisabled: {
    opacity: 0.6,
  },
  secondaryButtonText: {
    color: colors.text,
    fontWeight: fonts.weight.bold,
    fontSize: fonts.size.md,
  },
  secondaryButtonTextDisabled: {
    color: colors.textMuted,
  },
});

export default styles;
